name: rss_book
description: Read RSS feeds like it would be a good book
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.07.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: "^1.1.2"
  multiple_screens: "^0.2.0"  #Get rid of it after Flutter supports DSDs.
  dotted_line: "^3.0.0"
  dart_rss: "^1.0.1"
  http: "^0.12.2"
  url_launcher: "^6.0.3"
  font_awesome_flutter: "^9.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  ios: false
  android: true
  image_path: "assets/ic_launcher.png"

flutter:
  uses-material-design: true